name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: github-secrets  # Specify the environment where the secret is stored

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 using AdoptOpenJDK (correct distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget apt-transport-https gnupg lsb-release

      # Install Trivy
      - name: Install Trivy
        run: |
          # Add Trivy repository
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      # Run Trivy scan
      - name: Run Trivy scan
        run: |
          trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json --output trivy-report.json .

      # Debugging: Check if the Trivy report is generated correctly
      - name: Display Trivy report
        run: |
          cat trivy-report.json
          if [ ! -s trivy-report.json ]; then
            echo "Trivy report is empty"
            exit 1
          fi

      # Upload Trivy report as artifact (for download)
      - name: Upload Trivy report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: trivy-report.json

      # Provide the download link for the report (for human review)
      - name: Provide Trivy report download link
        run: |
          echo "Trivy report has been uploaded. You can download it from the artifacts tab in the GitHub Actions UI."
