name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: github-secrets

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 using AdoptOpenJDK (correct distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Install build tools
      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y make wget apt-transport-https gnupg lsb-release

      # Install Trivy
      - name: Install Trivy
        run: |
          # Add Trivy repository
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      # Run Trivy scan
      - name: Run Trivy scan
        run: |
          trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json --output trivy-report.json .

      # Debugging: Check if the Trivy report is generated correctly
      - name: Display Trivy report
        run: |
          cat trivy-report.json
          if [ ! -s trivy-report.json ]; then
            echo "Trivy report is empty"
            exit 1
          fi

      # Debugging: Check if DISCORD_WEBHOOK_URL is set
      - name: Check if DISCORD_WEBHOOK_URL is set
        run: |
          if [ -z "$DISCORD_WEBHOOK_URL" ]; then
            echo "DISCORD_WEBHOOK_URL is not set."
            exit 1
          else
            echo "DISCORD_WEBHOOK_URL is set correctly."
          fi

      # Send Trivy scan report to Discord
      - name: Send report to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Inject secret variable
        run: |
          # Send the report to Discord
          REPORT=$(cat trivy-report.json)
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"content\": \"Here is the Trivy scan report:\", \"embeds\":[{\"description\": \"$(echo "$REPORT" | jq . | head -c 1900)\"}]}" \
          $DISCORD_WEBHOOK_URL
