name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 17 using AdoptOpenJDK (correct distribution)
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install frontend dependencies and set up environment
      - name: Install frontend dependencies
        run: make frontend-install  # Use make frontend-install instead of npm install

      # Run Dockerfile lint checks
      - name: Run Dockerfile lint checks
        run: make lint

      # Run tests (frontend and backend)
      - name: Run tests
        run: make test

      # Build Maven package for backend
      - name: Build Maven package
        run: |
          cd shop-backend
          mvn clean package -DskipTests
          cd ..

      # Install Trivy
      - name: Install Trivy
        run: |
          sudo apt-get install -y trivy

      # Run Trivy scan
      - name: Run Trivy scan
        run: |
          trivy fs --exit-code 0 --severity HIGH,CRITICAL --format json --output trivy-report.json .

      # Send Trivy scan report to Discord
      - name: Send report to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Inject secret variable
        run: |
          REPORT=$(cat trivy-report.json)
          curl -X POST -H "Content-Type: application/json" \
          -d "{\"text\": \"Here is the Trivy scan report:\", \"attachments\":[{\"text\": \"$(echo "$REPORT" | jq . | head -c 1900)\"}]}" \
          $DISCORD_WEBHOOK_URL

      # Build Docker images (without pushing)
      - name: Build Docker images
        run: make docker-build-frontend docker-build-backend
